// 8x8 pixel sprites in the spirit of 1985 arcade hardware, drawn procedurally so no assets are needed.
// Each sprite is 8 rows of 8 characters; the palette maps characters to colours ('.' = transparent).
export const TILE = 16; // world tile in source pixels (8x8 art drawn at 2x)

const PAL = {
  '.': null,
  'k': '#000000', 'w': '#f4f4f4', 'g': '#9a9aa8', 'd': '#3a3a4c', 'b': '#2b2b3d', 'B': '#4a4a6a', 'f': '#14141f', 'F': '#1c1c2a',
  'r': '#e03c31', 'R': '#8f1f18', 'o': '#ff8c1a', 'y': '#f2c400', 'Y': '#fff28a', 'l': '#3b7dff', 'L': '#1f4fb0', 'e': '#2ecc40', 'E': '#187f27',
  'p': '#a05cff', 'P': '#5a2d99', 'n': '#c97b3a', 'N': '#7a4520', 's': '#e8c39e', 'c': '#5cd6ff', 't': '#b0b0c0',
};

const SPR = {
  wall: [
    'BBBBBBBB',
    'BbbbBbbb',
    'BBBBBBBB',
    'bbBbbbBb',
    'BBBBBBBB',
    'BbbbBbbb',
    'BBBBBBBB',
    'bbBbbbBb',
  ],
  floor: [
    'ffffffff',
    'fFffffff',
    'ffffffFf',
    'ffffffff',
    'fffFffff',
    'ffffffff',
    'fFffffFf',
    'ffffffff',
  ],
  trap: [ // secret wall: like wall but with a hairline crack
    'BBBBBBBB',
    'BbbbBbbb',
    'BBBBBBfB',
    'bbBbbfBb',
    'BBBBfBBB',
    'BbbfBbbb',
    'BBfBBBBB',
    'bbBbbbBb',
  ],
  door: [
    'yyyyyyyy',
    'y.y..y.y',
    'y.y..y.y',
    'yyyyyyyy',
    'y.y..y.y',
    'y.y..y.y',
    'yyyyyyyy',
    'y.y..y.y',
  ],
  key: [
    '........',
    '.yyy....',
    'y...y...',
    'y...yyyy',
    'y...y.y.',
    '.yyy..y.',
    '........',
    '........',
  ],
  food: [
    '........',
    '...nnn..',
    '..nnnnn.',
    '.nnnnnnn',
    '.nNnnnNn',
    '..nnnnn.',
    '...ww...',
    '..w..w..',
  ],
  potion: [
    '...tt...',
    '...cc...',
    '...cc...',
    '..cccc..',
    '.cccccc.',
    '.clcccc.',
    '.cccccc.',
    '..cccc..',
  ],
  treasure: [
    '........',
    '.NNNNNN.',
    'NyyyyyyN',
    'NyNNNNyN',
    'NNNyyNNN',
    'NyNNNNyN',
    'NyyyyyyN',
    '.NNNNNN.',
  ],
  exit: [
    'gggggggg',
    'gdddddgg',
    'gdkkkkdg',
    'gdkkkkdg',
    'gdkkkkdg',
    'gdkkkkdg',
    'gddddddg',
    'gggggggg',
  ],
  gen1: [ // ghost/grunt/demon generators share a bone pile shape, tinted by type
    '........',
    '........',
    '..w..w..',
    '.wwwwww.',
    '.wkwwkw.',
    '.wwwwww.',
    '.w.ww.w.',
    'wwwwwwww',
  ],
  gen2: [
    '........',
    '..w..w..',
    '.wwwwww.',
    '.wkwwkw.',
    '.wwwwww.',
    'w.w.ww.w',
    'wwwwwwww',
    'wwwwwwww',
  ],
  gen3: [
    '..w..w..',
    '.wwwwww.',
    '.wkwwkw.',
    '.wwwwww.',
    'w.wwww.w',
    'wwwwwwww',
    'wwwwwwww',
    'wwwwwwww',
  ],
  ghost: [
    '..wwww..',
    '.wwwwww.',
    '.wkwwkw.',
    '.wwwwww.',
    '.wwwwww.',
    '.wwwwww.',
    '.wwwwww.',
    '.w.ww.w.',
  ],
  grunt: [
    '..nnnn..',
    '.nnnnnn.',
    '.nknnkn.',
    '.nnnnnn.',
    'NNnnnnNN',
    'N.nnnn.N',
    '..NNNN..',
    '..N..N..',
  ],
  demon: [
    'r......r',
    '.r....r.',
    '.rrrrrr.',
    '.rYrrYr.',
    '.rrrrrr.',
    'rrRrrRrr',
    '..rrrr..',
    '..r..r..',
  ],
  death: [
    '..kkkk..',
    '.kwwwwk.',
    '.kwkwkwk',
    '.kwwwwk.',
    '..kwwk..',
    '.kkkkkk.',
    '.kkkkkk.',
    '.k.kk.k.',
  ],
  lobber: [ // squat blob that keeps its distance and lobs shots over walls
    '........',
    '..pppp..',
    '.pPppPp.',
    '.pppppp.',
    'ppkppkpp',
    '.pppppp.',
    '.p.pp.p.',
    '........',
  ],
  sorcerer: [ // hooded caster; blinks in and out of visibility
    '...LL...',
    '..LllL..',
    '.LlkklL.',
    '.Lllllt.',
    '.ltlllt.',
    '..ltlt..',
    '..l..l..',
    '.k....k.',
  ],
  thief: [ // fast, sneaky, hooded
    '..dddd..',
    '.dkkkkd.',
    '.dkrrkd.',
    '.dkkkkd.',
    'ddnnnndd',
    'd.nnnn.d',
    '..dd.dd.',
    '..d..d..',
  ],
  transporter: [ // swirling portal — drawn with a time-based pulse in client/game.js
    '.cccccc.',
    'cclLllcc',
    'clLccLlc',
    'clLcccLc',
    'clLcccLc',
    'clLccLlc',
    'cclLllcc',
    '.cccccc.',
  ],
  poisonfood: [ // looks like food, but green — costs health instead
    '........',
    '...eee..',
    '..eeeee.',
    '.eeeeeee',
    '.eEeeeEe',
    '..eeeee.',
    '...ww...',
    '..w..w..',
  ],
  cider: [ // +50 health drink
    '........',
    '.NNNNN..',
    '.NyyyN..',
    '.NyyyN..',
    '.NyyyN..',
    '.NNNNN..',
    '..NN....',
    '........',
  ],
  amulet_invis: [ // invisibility amulet: a hollow, see-through cyan ring
    '..cccc..',
    '.c....c.',
    'c..tt..c',
    'c.t..t.c',
    'c.t..t.c',
    'c..tt..c',
    '.c....c.',
    '..cccc..',
  ],
  amulet_reflect: [ // reflective-shots amulet: a shiny silver/white shard
    '...w....',
    '..www...',
    '.wwwww..',
    'wwwwwww.',
    '.wwwww..',
    '..www...',
    '...w....',
    '........',
  ],
  amulet_repulse: [ // repulsiveness amulet: a purple shockwave burst
    '..p..p..',
    '.p.pp.p.',
    'p.pppp.p',
    '.pppppp.',
    'p.pppp.p',
    '.p.pp.p.',
    '..p..p..',
    '........',
  ],
  amulet_super: [ // super-shots amulet: an orange/yellow starburst
    '...o....',
    '..ooo...',
    '.ooYoo..',
    'oooYooo.',
    '.ooYoo..',
    '..ooo...',
    '...o....',
    '........',
  ],
  boost_speed: [ // permanent speed boost: blue badge
    '..tttt..',
    '.t....t.',
    't.llll.t',
    't.llll.t',
    't.llll.t',
    't.llll.t',
    '.t....t.',
    '..tttt..',
  ],
  boost_armor: [ // permanent armor boost: white/steel badge
    '..tttt..',
    '.t....t.',
    't.wwww.t',
    't.wwww.t',
    't.wwww.t',
    't.wwww.t',
    '.t....t.',
    '..tttt..',
  ],
  boost_shot: [ // permanent shot-power boost: red badge
    '..tttt..',
    '.t....t.',
    't.rrrr.t',
    't.rrrr.t',
    't.rrrr.t',
    't.rrrr.t',
    '.t....t.',
    '..tttt..',
  ],
  boost_firerate: [ // permanent shot-speed boost: yellow badge
    '..tttt..',
    '.t....t.',
    't.yyyy.t',
    't.yyyy.t',
    't.yyyy.t',
    't.yyyy.t',
    '.t....t.',
    '..tttt..',
  ],
  boost_magic: [ // permanent magic-power boost: purple badge
    '..tttt..',
    '.t....t.',
    't.pppp.t',
    't.pppp.t',
    't.pppp.t',
    't.pppp.t',
    '.t....t.',
    '..tttt..',
  ],
  exit2: [ // skip-exit variant: jumps the party ahead 4 levels
    'yyyyyyyy',
    'ydddddyy',
    'ydokkkoy',
    'ydokkkoy',
    'ydokkkoy',
    'ydokkkoy',
    'yddddddy',
    'yyyyyyyy',
  ],
  lob: [ // lobber's arcing shot
    '........',
    '..nnnn..',
    '.nNnnNn.',
    '.nnnnnn.',
    '.nNnnNn.',
    '.nnnnnn.',
    '..nnnn..',
    '........',
  ],
  hero: [ // body tinted per class (colour 'r' replaced), skin 's'
    '..ssss..',
    '..sksk..',
    '..ssss..',
    '.rrrrrr.',
    'srrrrrrs',
    '.rrrrrr.',
    '..rr.rr.',
    '..kk.kk.',
  ],
  axe: [
    '........',
    '..tt....',
    '.ttt....',
    '.tttn...',
    '..ttnn..',
    '.....nn.',
    '......n.',
    '........',
  ],
  sword: [
    '........',
    '......t.',
    '.....tt.',
    '....tt..',
    '...tt...',
    '..yy....',
    '.yn.....',
    '........',
  ],
  fireball: [
    '........',
    '...oo...',
    '..oyyo..',
    '.oyYYyo.',
    '.oyYYyo.',
    '..oyyo..',
    '...oo...',
    '........',
  ],
  arrow: [
    '........',
    '........',
    '.......e',
    '.nnnnnee',
    '.....eee',
    '.......e',
    '........',
    '........',
  ],
  dfire: [
    '........',
    '...rr...',
    '..roor..',
    '.royyor.',
    '.royyor.',
    '..roor..',
    '...rr...',
    '........',
  ],
  hammer: [ // paladin: heavy war hammer
    '........',
    '..tttt..',
    '.tttttt.',
    '.tttttt.',
    '..nnnn..',
    '...nn...',
    '...nn...',
    '........',
  ],
  dagger: [ // ranger: quick thrown blade
    '........',
    '.....t..',
    '....tt..',
    '...tt...',
    '..tt....',
    '.nn.....',
    '.n......',
    '........',
  ],
  skull: [ // necromancer: bone bolt
    '........',
    '..pppp..',
    '.pppppp.',
    '.pkppkp.',
    '.pppppp.',
    '..pppp..',
    '.p.pp.p.',
    '........',
  ],
};

const cache = new Map();
export function sprite(name, tint = null, scale = 2) {
  const key = `${name}|${tint || ''}|${scale}`;
  if (cache.has(key)) return cache.get(key);
  const rows = SPR[name];
  const c = document.createElement('canvas');
  c.width = 8 * scale; c.height = 8 * scale;
  const ctx = c.getContext('2d');
  for (let y = 0; y < 8; y++) for (let x = 0; x < 8; x++) {
    const ch = rows[y][x];
    let col = PAL[ch];
    if (tint && (ch === 'r' || ch === 'w') && name !== 'ghost' && name !== 'death' && name !== 'demon') col = ch === 'r' ? tint : tint;
    if (!col) continue;
    ctx.fillStyle = col;
    ctx.fillRect(x * scale, y * scale, scale, scale);
  }
  cache.set(key, c);
  return c;
}

export const GEN_TINT = { g: '#c97b3a', h: '#f4f4f4', m: '#e03c31', l: '#a05cff', s: '#3b7dff' };
export const TILE_SPRITE = {
  '#': 'wall', '.': 'floor', 'D': 'door', 'K': 'key', 'F': 'food', 'P': 'potion', 'T': 'treasure',
  'E': 'exit', 'S': 'floor', 'W': 'trap', 'X': 'transporter', '!': 'poisonfood', 'C': 'cider', '8': 'exit2',
  'I': 'amulet_invis', 'R': 'amulet_reflect', 'O': 'amulet_repulse', 'U': 'amulet_super',
  'V': 'boost_speed', 'A': 'boost_armor', 'B': 'boost_shot', 'Q': 'boost_firerate', 'N': 'boost_magic',
};
// 'c' = a Hero Builder custom hero's shot (see shared/hero-builder.js toClassDef's shotKey) — every
// custom hero shares this one letter regardless of weapon, so client/game.js overrides this default
// per-shot using the owner's own `weapon` id (which doubles as its sprite name — see WEAPONS below).
export const SHOT_SPRITE = { w: 'axe', v: 'sword', z: 'fireball', e: 'arrow', d: 'dfire', p: 'hammer', r: 'dagger', n: 'skull', a: 'lob', c: 'dagger' };
