// Narrator voice pipeline (#19): say(lineId, text) first tries a pre-rendered clip at
// /audio/voice/<lineId>.ogg (listed in client/audio/voice/manifest.json, generated by
// tools/generate-voice.mjs), and falls back to the browser's speechSynthesis with the game's
// existing robotic settings when no clip is available. The repo ships 13 pre-rendered clips
// (every narrator line except the per-scene `cutscene` caption, whose text differs every time so
// it's never pre-rendered) committed under client/audio/voice/ — speechSynthesis is only a
// fallback now, used for the `cutscene` id or if a shipped clip ever fails to load. Every line
// runs through the voice mixer volume (see client/audio.js's sibling master/SFX buses — voice
// deliberately has no WebAudio graph of its own since both playback paths, HTMLAudio and
// speechSynthesis, use their own native volume knobs).
import { isMuted, onMuteChange } from './audio.js';

const VOICE_VOL_KEY = 'gc_vol_voice';
const MIN_GAP_MS = 2500; // narrator lines are rate-limited so they don't talk over each other

// Cancel any in-flight clip/speechSynthesis the instant mute is turned on, rather than waiting
// for whatever line is currently playing to finish.
onMuteChange((muted) => { if (muted) stopSpeaking(); });

function readVoiceVolume() {
  try {
    const v = localStorage.getItem(VOICE_VOL_KEY);
    const n = v == null ? 100 : Number(v);
    return Number.isFinite(n) ? Math.max(0, Math.min(100, n)) / 100 : 1;
  } catch { return 1; }
}

let manifestPromise = null;
function loadManifest() {
  if (!manifestPromise) {
    manifestPromise = fetch('/audio/voice/manifest.json')
      .then((r) => (r.ok ? r.json() : {}))
      .catch(() => ({}));
  }
  return manifestPromise;
}

let currentAudio = null;
function playClip(id) {
  return loadManifest().then((manifest) => {
    // The manifest fetch is async; mute may have been toggled on while it was in flight. Bail
    // out of starting playback rather than winning a race against the mute the user just asked
    // for (stopSpeaking() above can't cancel an Audio element that hasn't started playing yet).
    if (isMuted()) return false;
    if (!manifest || !manifest[id]) return false;
    return new Promise((resolve) => {
      try {
        const a = new Audio(`/audio/voice/${id}.ogg`);
        a.volume = readVoiceVolume();
        a.addEventListener('ended', () => resolve(true), { once: true });
        a.addEventListener('error', () => resolve(false), { once: true });
        currentAudio = a;
        a.play().catch(() => resolve(false));
      } catch { resolve(false); }
    });
  }).catch(() => false);
}

function speak(text) {
  if (!text || !('speechSynthesis' in window)) return;
  const u = new SpeechSynthesisUtterance(text);
  u.rate = 0.9; u.pitch = 0.6; u.volume = readVoiceVolume();
  speechSynthesis.speak(u);
}

let lastSay = 0;
// Bumped on every say() call and every mute-on toggle; a playClip() continuation only speaks if
// it's still the most recent call *and* mute hasn't won the race while the manifest fetch was
// in flight (see onMuteChange() above, which also bumps this to invalidate any pending say()).
let sayGeneration = 0;
onMuteChange((muted) => { if (muted) sayGeneration++; });

/** Speak narrator line `lineId` (falling back to speechSynthesis of `text` if no clip exists).
 *  Rate-limited across all lines, same as the game's previous inline say(). Callers are expected
 *  to gate this on their own narrator-enabled preference (see client/game.js's G.narrate). */
export function say(lineId, text) {
  if (isMuted()) return; // honor the global mute flag (client/audio.js) for both playback paths
  const now = (typeof performance !== 'undefined' ? performance.now() : Date.now());
  if (now - lastSay < MIN_GAP_MS) return;
  lastSay = now;
  const generation = ++sayGeneration;
  playClip(lineId).then((played) => {
    // Mute may have been toggled on (or another say() started) while the manifest/clip fetch was
    // in flight -- re-check before actually speaking so a mute toggled mid-flight always wins.
    if (generation !== sayGeneration || isMuted()) return;
    if (!played) speak(text ?? lineId);
  });
}

export function stopSpeaking() {
  try { if (currentAudio) { currentAudio.pause(); currentAudio = null; } } catch {}
  try { if ('speechSynthesis' in window) speechSynthesis.cancel(); } catch {}
}
