// Narrator voice pipeline (#19): say(lineId, text) first tries a pre-rendered clip at
// /audio/voice/<lineId>.ogg (listed in client/audio/voice/manifest.json, generated by
// tools/generate-voice.mjs), and falls back to the browser's speechSynthesis with the game's
// existing robotic settings when no clip is available (the manifest ships empty, so every line
// falls back to speechSynthesis until clips are generated). Every line runs through the voice
// mixer volume (see client/audio.js's sibling master/SFX buses — voice deliberately has no
// WebAudio graph of its own since both playback paths, HTMLAudio and speechSynthesis, use their
// own native volume knobs).
import { isMuted, onMuteChange } from './audio.js';

const VOICE_VOL_KEY = 'gc_vol_voice';
const MIN_GAP_MS = 2500; // narrator lines are rate-limited so they don't talk over each other

// Cancel any in-flight clip/speechSynthesis the instant mute is turned on, rather than waiting
// for whatever line is currently playing to finish.
onMuteChange((muted) => { if (muted) stopSpeaking(); });

function readVoiceVolume() {
  try {
    const v = localStorage.getItem(VOICE_VOL_KEY);
    const n = v == null ? 100 : Number(v);
    return Number.isFinite(n) ? Math.max(0, Math.min(100, n)) / 100 : 1;
  } catch { return 1; }
}

let manifestPromise = null;
function loadManifest() {
  if (!manifestPromise) {
    manifestPromise = fetch('/audio/voice/manifest.json')
      .then((r) => (r.ok ? r.json() : {}))
      .catch(() => ({}));
  }
  return manifestPromise;
}

let currentAudio = null;
function playClip(id) {
  return loadManifest().then((manifest) => {
    if (!manifest || !manifest[id]) return false;
    return new Promise((resolve) => {
      try {
        const a = new Audio(`/audio/voice/${id}.ogg`);
        a.volume = readVoiceVolume();
        a.addEventListener('ended', () => resolve(true), { once: true });
        a.addEventListener('error', () => resolve(false), { once: true });
        currentAudio = a;
        a.play().catch(() => resolve(false));
      } catch { resolve(false); }
    });
  }).catch(() => false);
}

function speak(text) {
  if (!text || !('speechSynthesis' in window)) return;
  const u = new SpeechSynthesisUtterance(text);
  u.rate = 0.9; u.pitch = 0.6; u.volume = readVoiceVolume();
  speechSynthesis.speak(u);
}

let lastSay = 0;
/** Speak narrator line `lineId` (falling back to speechSynthesis of `text` if no clip exists).
 *  Rate-limited across all lines, same as the game's previous inline say(). Callers are expected
 *  to gate this on their own narrator-enabled preference (see client/game.js's G.narrate). */
export function say(lineId, text) {
  if (isMuted()) return; // honor the global mute flag (client/audio.js) for both playback paths
  const now = (typeof performance !== 'undefined' ? performance.now() : Date.now());
  if (now - lastSay < MIN_GAP_MS) return;
  lastSay = now;
  playClip(lineId).then((played) => { if (!played) speak(text ?? lineId); });
}

export function stopSpeaking() {
  try { if (currentAudio) { currentAudio.pause(); currentAudio = null; } } catch {}
  try { if ('speechSynthesis' in window) speechSynthesis.cancel(); } catch {}
}
